# Generated by Django 5.1.5 on 2025-03-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='initial',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
